<?php

declare(strict_types=1);

namespace Reactiph\Component;

use PhpParser\Node;
use PhpParser\Node\Stmt;
use PhpParser\ParserFactory;

/**
 * Auto-registers every component found in a directory, instead of calling
 * {@see ComponentRegistry::register()} by hand for each one — the
 * "folder-based component" auto-discovery half of ADR 0020 (the other half
 * is {@see BaseComponent}'s default `template()` sibling-file lookup).
 *
 * A discovered component is tagged under its own short class name (e.g.
 * `Counter.php` declaring `final class Counter extends BaseComponent`
 * anywhere under the scanned directory registers `<Counter />`) — there is
 * currently no way to choose a different tag name for an auto-discovered
 * component; register it manually via {@see ComponentRegistry::register()}
 * instead if that's needed.
 */
final class ComponentDiscovery
{
    /**
     * Recursively scans `$directory` for `.php` files, statically
     * determines each one's declared class — via `nikic/php-parser`,
     * never by `include`-ing or `eval`-ing the file itself — and
     * registers every concrete `BaseComponent` subclass found.
     *
     * A discovered class must still resolve through the normal Composer
     * autoloader (PSR-4): this only parses a file far enough to learn its
     * declared class name, then leans on `class_exists()` to actually
     * load it the ordinary way. A class whose file doesn't sit where its
     * own namespace's PSR-4 mapping expects simply won't autoload, and is
     * silently skipped here too — same as it would be anywhere else in
     * the application.
     *
     * Runs a fresh filesystem scan and re-parses every file on every
     * call — deliberately simple for the framework's current maturity,
     * not cached. A cached manifest generated by a build step is natural
     * follow-on work (see Part 8's CLI/dev tooling in the roadmap), not
     * built here.
     */
    public static function registerDirectory(string $directory): void
    {
        foreach (self::findComponentClasses($directory) as $class) {
            ComponentRegistry::register((new \ReflectionClass($class))->getShortName(), $class);
        }
    }

    /**
     * @return list<class-string<BaseComponent>>
     */
    private static function findComponentClasses(string $directory): array
    {
        if (!is_dir($directory)) {
            return [];
        }

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($directory, \FilesystemIterator::SKIP_DOTS),
        );

        /** @var list<class-string<BaseComponent>> $classes */
        $classes = [];

        foreach ($iterator as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }

            $class = self::classNameFromFile($file->getPathname());

            if ($class === null || !class_exists($class) || !is_subclass_of($class, BaseComponent::class)) {
                continue;
            }

            if ((new \ReflectionClass($class))->isAbstract()) {
                continue;
            }

            $classes[] = $class;
        }

        return $classes;
    }

    /**
     * Parses just enough of a PHP file to find its one declared top-level
     * class name (namespaced or not) — the file is never included or
     * evaluated, only parsed as an AST. Returns null for a file that
     * declares no class, declares more than one, or fails to parse (a
     * genuinely broken file shouldn't halt discovery for every other
     * component in the directory).
     */
    private static function classNameFromFile(string $file): ?string
    {
        $source = file_get_contents($file);

        if ($source === false) {
            return null;
        }

        try {
            $ast = (new ParserFactory())->createForHostVersion()->parse($source);
        } catch (\PhpParser\Error) {
            return null;
        }

        if ($ast === null) {
            return null;
        }

        return self::findClassName($ast, '');
    }

    /**
     * @param Node[] $nodes
     */
    private static function findClassName(array $nodes, string $namespace): ?string
    {
        foreach ($nodes as $node) {
            if ($node instanceof Stmt\Namespace_) {
                $found = self::findClassName($node->stmts, $node->name?->toString() ?? '');

                if ($found !== null) {
                    return $found;
                }
            }

            if ($node instanceof Stmt\Class_ && $node->name !== null) {
                return $namespace === '' ? $node->name->toString() : $namespace . '\\' . $node->name->toString();
            }
        }

        return null;
    }
}
